[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bago"
version = "0.0.6"
authors = [
  { name="Huaxu", email="yhxchem@outlook.com" },
]
maintainers = [
  { name="Huaxu", email="yhxchem@outlook.com" },
]
description = "LC gradient optimization and evaluation"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Waddlessss/BAGO"